-- MySQL Script generated by MySQL Workbench
-- Fri May 24 10:10:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clientdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clientdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clientdb` DEFAULT CHARACTER SET utf8 ;
USE `clientdb` ;

-- -----------------------------------------------------
-- Table `clientdb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientdb`.`client` ;

CREATE TABLE IF NOT EXISTS `clientdb`.`client` (
  `ClientId` CHAR(36) NOT NULL,
  `ClientName` NVARCHAR(60) NOT NULL,
  `Email` NVARCHAR(60) NOT NULL,
  `FirstName` NVARCHAR(60) NOT NULL,
  `LastName` NVARCHAR(60) NOT NULL,
  `PhoneNo` NVARCHAR(60) NOT NULL,
  `MobileNo` NVARCHAR(60) NOT NULL,
  `StreetAddr` NVARCHAR(100) NOT NULL,
  `City` NVARCHAR(60) NOT NULL,
  `State` NVARCHAR(60) NOT NULL,
  `Country` NVARCHAR(60) NOT NULL,
  `Industry` NVARCHAR(60) NOT NULL,
  `Description` NVARCHAR(200) NOT NULL,
  PRIMARY KEY (`ClientId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;